// <auto-generated />
using System;
using GDi.WinterAcademy.Demo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GDi.WinterAcademy.Demo.Infrastructure.Migrations
{
    [DbContext(typeof(WinterAcademyDemoDbContext))]
    partial class WinterAcademyDemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GDi.WinterAcademy.Demo.Core.Entities.Actor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateOfBirth = new DateTime(1947, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arnold Schwarzenegger",
                            Nationality = "Austrian-American"
                        },
                        new
                        {
                            Id = 2L,
                            DateOfBirth = new DateTime(1978, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Zoe Salanda",
                            Nationality = "American"
                        });
                });

            modelBuilder.Entity("GDi.WinterAcademy.Demo.Core.Entities.Movie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<long>("MainCharacterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MainCharacterId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Duration = 107,
                            MainCharacterId = 1L,
                            ReleaseDate = new DateTime(1984, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Terminator"
                        },
                        new
                        {
                            Id = 2L,
                            Duration = 107,
                            MainCharacterId = 1L,
                            ReleaseDate = new DateTime(1987, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Predator"
                        },
                        new
                        {
                            Id = 3L,
                            Duration = 192,
                            MainCharacterId = 2L,
                            ReleaseDate = new DateTime(2022, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar: The Way of Water"
                        });
                });

            modelBuilder.Entity("GDi.WinterAcademy.Demo.Core.Entities.Movie", b =>
                {
                    b.HasOne("GDi.WinterAcademy.Demo.Core.Entities.Actor", "MainCharacter")
                        .WithMany("Movies")
                        .HasForeignKey("MainCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCharacter");
                });

            modelBuilder.Entity("GDi.WinterAcademy.Demo.Core.Entities.Actor", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
